site_name: Shadowrun 6 Regeln
theme:
  name: material
repo_url: https://github.com/mvach/shadowrun6

site_name: Navigation
nav:
  - Home: index.md
  - kampf.md
  - proben.md
  - handlungen.md
  - fertigkeiten.md
  - status.md
  - barrieren.md
  - schloesser.md
  - waffen.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences