site_name: Shadowrun 6 Regeln
theme:
  name: material
repo_url: https://github.com/mvach/shadowrun6

site_name: Navigation
nav:
  - Home: index.md
  - kampf.md
  - proben.md
  - handlungen.md
  - fertigkeiten.md
  - status.md
  - barrieren.md
  - schloesser.md
  - waffen.md

extra_css:
  - stylesheets/extra.css